[project]
name = "sdl-rdp"
cmake_option_prefix = "BACKEND"
module_define_prefix = "BACKEND"

[cmake]
extensions = []

[modules.SDL3]
soversion = 0

[options]
contracts = "stop"

[run]
default = "sdl-rdp-sample"

[package]
kind = "library"
name = "sdl-rdp"

[test]
exclude_labels = ["sdl-rdp-bench"]
