[project]
name = "sdl-rdp"
cmake_option_prefix = "BACKEND"
module_define_prefix = "BACKEND"

[cmake]
extensions = []

[options]
sdl_version = "3.4.8"
contracts = "stop"

[run]
default = "sdl-rdp-sample"

[package]
kind = "library"
name = "sdl-rdp"

[test]
exclude_labels = ["bench"]
