[project]
name = "sdl-rdp"
cmake_option_prefix = "BACKEND"
module_define_prefix = "BACKEND"
cxx_standard = 26

[cmake]
extensions = []

[options]
contracts = "stop"

[run]
default = "sample"

[package]
kind = "library"
name = "sdl-rdp"
